sudo: required

enabled: false

language: ruby

services:
  - docker

# whitelist
branches:
  only:
    - master

git:
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - sed -i 's/git@gist.github.com:/https:\/\/gist.github.com\//' .gitmodules
  - git submodule update --init --recursive
  - cd cellorganizer-python
  - git checkout master
  - cd ..  

script:
  - docker build --no-cache -t murphylab/cellorganizer-jupyter:latest .
  - docker images list
