sudo: required

enabled: false

language: ruby

services:
  - docker

# whitelist
branches:
  only:
    - master

git:
  submodules: false

before_install:
  - git submodule init
  - git submodule update 
  - cd cellorganizer-python
  - git checkout master
  - cd ..  

script:
  - docker build --no-cache -t murphylab/cellorganizer-jupyter:latest .
  - docker images list
